name=OracleUplink
version=1.0.0
author=Wayne Tech Enterprises
maintainer=Wayne Tech Enterprises
sentence=Modular multi-transport bridge library for the Oracle Network.
paragraph=Seamlessly integrate your DIY microcontrollers via BLE or USB to the Oracle Network dashboard using JSON payloads.
category=Communication
url=https://github.com/Ghost3379/Oracle-Uplink
architectures=esp32
depends=NimBLE-Arduino, ArduinoJson
